In [4]:
'''
EXERCÍCIO 01
'''

# Vitórias no futebol americano (população)

import pandas as pd

vitorias = pd.Series([13, 10, 12, 11, 7, 8, 6, 6,
                      10, 7, 12, 4, 6, 5, 2, 2])

v_max = vitorias.max()
v_min = vitorias.min()

amplitude = v_max - v_min
print(f'A amplitude sobre as vitorias no futebol americano é {amplitude}')

media = vitorias.mean()
print(f'A média sobre as vitorias no futebol americano é {media:.2f}')

variancia = vitorias.var(ddof=0) # ddof=0 => desvio padrão populacional
print(f'A variância sobre as vitorias no futebol americano é {variancia:.2f}')

desvio_padrao = vitorias.std()
print(f'O desvio padrão sobre as vitorias no futebol americano é {desvio_padrao:.2f}')

A amplitude sobre as vitorias no futebol americano é 11
A média sobre as vitorias no futebol americano é 7.56
A variância sobre as vitorias no futebol americano é 12.13
O desvio padrão sobre as vitorias no futebol americano é 3.48

In [7]:
# Pesos (em libras) dos presidentes (população)

pesos = pd.Series([173, 175, 200, 173, 160, 185, 195, 230, 190, 180])

p_max = pesos.max()
p_min = pesos.min()

amplitude = p_max - p_min
print(f'A amplitude sobre os pesos dos presidentes é {amplitude}')

media = pesos.mean()
print(f'A média sobre os pesos dos presidentes é {media:.2f}')

variancia = pesos.var(ddof=0) # ddof=0 => desvio padrão populacional
print(f'A variância sobre os pesos dos presidentes é {variancia:.2f}')

desvio_padrao = pesos.std()
print(f'O desvio padrão sobre os pesos dos presidentes é {desvio_padrao:.2f}')

A amplitude sobre os pesos dos presidentes é 70
A média sobre os pesos dos presidentes é 186.10
A variância sobre os pesos dos presidentes é 377.88
O desvio padrão sobre os pesos dos presidentes é 19.44

In [12]:
'''
EXERCÍCIO 02
'''

# Idade de consumidores (amostra)

import pandas as pd

idades = pd.Series([16, 18, 19, 17, 14, 15, 17, 17, 17, 16,
                    19, 22, 24, 14, 16, 14, 17, 16, 14, 18])

i_max = idades.max()
i_min = idades.min()

amplitude = i_max - i_min
print(f'A amplitude sobre as idades dos consumidores é {amplitude}')

media = idades.mean()
print(f'A média sobre as idades dos consumidores é {media:.2f}')

variancia = idades.var(ddof=1) # ddof=1 => desvio padrão amostral
print(f'A variância sobre as idades dos consumidores é {variancia:.2f}')

desvio_padrao = idades.std()
print(f'O desvio padrão sobre as idades dos consumidores é {desvio_padrao:.2f}')

A amplitude sobre as idades dos consumidores é 10
A média sobre as idades dos consumidores é 17.00
A variância sobre as idades dos consumidores é 6.40
O desvio padrão sobre as idades dos consumidores é 2.60

In [13]:
# Tempo de gestação (em dias) (amostra)

duracao = pd.Series([277, 291, 295, 280, 268, 278, 291,
                     277, 282, 279, 296, 285, 269, 293,
                     267, 281, 286, 269, 264, 299])

d_max = duracao.max()
d_min = duracao.min()

amplitude = d_max - d_min
print(f'A amplitude sobre os tempos de gestação é {amplitude}')

media = duracao.mean()
print(f'A média sobre os tempos de gestação é {media:.2f}')

variancia = duracao.var(ddof=1) # ddof=1 => desvio padrão amostral
print(f'A variância sobre os tempos de gestação é {variancia:.2f}')

desvio_padrao = duracao.std()
print(f'O desvio padrão sobre os tempos de gestação é {desvio_padrao:.2f}')

A amplitude sobre os tempos de gestação é 35
A média sobre os tempos de gestação é 281.35
A variância sobre os tempos de gestação é 111.40
O desvio padrão sobre os tempos de gestação é 10.55

In [ ]:
'''
EXERCÍCIO 03
'''

# O desvio padrao de 2.4 pertence ao histograma (a) devido à baixa dispersão dos dados,
# enquanto o desvio padrao de 5 pertence ao histograma (b) devido à alta dispersão dos dados.

In [ ]:
'''
EXERCÍCIO 04
'''

# A

# O maior desvio padrão pertence ao histograma (ii) devido à alta dispersão dos dados,
# enquanto o menor desvio padrão pertence ao histograma (iii) devido à baixa dispersão dos dados.

# B

# Os conjuntos de dados se asemelham na questão da média, devido aos tres possuirem 
# unidades de medida e média próximas entre elas. Eles se diferem em sua frequencia.

In [16]:
'''
EXERCÍCIO 05
'''

# Carros por domicílio

dados = pd.DataFrame({'Freq (f)': [3, 15, 24, 8],
                      'Pt. médio (x)': [0, 1, 2, 3]})

dados['x*f'] = dados['Freq (f)'] * dados['Pt. médio (x)']

# Cálculo da média
## Seu código aqui!!!
media_dados = dados['Pt. médio (x)'].mean()

# Coluna valor - média
## Seu código aqui!!!
dados['x-xbarra'] = dados['Pt. médio (x)'] - media_dados

# Coluna (valor - média)^2
## Seu código aqui!!!
dados['(x-xbarra)^2'] = dados['x-xbarra']**2

# Coluna (valor - média)^2 * frequência
## Seu código aqui!!!
dados['(x-xbarra)^2*f'] = dados['(x-xbarra)^2'] * dados['Freq (f)']
display(dados) 
# Cálculo da média amostral
## Seu código aqui!!!
obs = dados['Freq (f)'].sum()
media_amostral = dados['x*f'].sum() / obs
print(f'Media amostral: {media_amostral:.1f} carros por domicílio')
# Cálculo do desvio padrão amostral
## Seu código aqui!!!
desvpadrao_amostral = (dados['(x-xbarra)^2*f'].sum() / (obs-1))**(1/2)
print(f'Desvio padrao amostral: {desvpadrao_amostral:.1f} carros por domicílio')

   Freq (f)  Pt. médio (x)  x*f  x-xbarra  (x-xbarra)^2  (x-xbarra)^2*f
0         3              0    0      -1.5          2.25            6.75
1        15              1   15      -0.5          0.25            3.75
2        24              2   48       0.5          0.25            6.00
3         8              3   24       1.5          2.25           18.00

Media amostral: 1.7 carros por domicílio
Desvio padrao amostral: 0.8 carros por domicílio

In [19]:
# Renda Familiar 

dados = pd.DataFrame({'Classe':['$0 - $1999', '$2000 - $3999', 
                                '$4000 - $5999', '$6000 - $7999', 
                                '$8000 - $9999', '$10000 - ou+'],
                      'Freq (f)': [11, 12, 20, 10, 13, 10],
                      'Pt. médio (x)': [999.50, 2999.50, 4999.50, 
                                        6999.50, 8999.50, 10999.50]})

dados['x*f'] = dados['Freq (f)'] * dados['Pt. médio (x)']

# Cálculo da média
## Seu código aqui!!!
media_dados = dados['Pt. médio (x)'].mean()

# Coluna valor - média
## Seu código aqui!!!
dados['x-xbarra'] = dados['Pt. médio (x)'] - media_dados

# Coluna (valor - média)^2
## Seu código aqui!!!
dados['(x-xbarra)^2'] = dados['x-xbarra']**2

# Coluna (valor - média)^2 * frequência
## Seu código aqui!!!
dados['(x-xbarra)^2*f'] = dados['(x-xbarra)^2'] * dados['Freq (f)']
display(dados) 
# Cálculo da média amostral
## Seu código aqui!!!
obs = dados['Freq (f)'].sum()
media_amostral = dados['x*f'].sum() / obs
print(f'Media amostral: {media_amostral:.1f} renda familiar')
# Cálculo do desvio padrão amostral
## Seu código aqui!!!
desvpadrao_amostral = (dados['(x-xbarra)^2*f'].sum() / (obs-1))**(1/2)
print(f'Desvio padrao amostral: {desvpadrao_amostral:.1f} renda familiar')

,Classe,Freq (f),Pt. médio (x),x*f,x-xbarra,(x-xbarra)^2,(x-xbarra)^2*f
0,$0 - $1999,11,999.5,10994.5,-5000.0,25000000.0,275000000.0
1,$2000 - $3999,12,2999.5,35994.0,-3000.0,9000000.0,108000000.0
2,$4000 - $5999,20,4999.5,99990.0,-1000.0,1000000.0,20000000.0
3,$6000 - $7999,10,6999.5,69995.0,1000.0,1000000.0,10000000.0
4,$8000 - $9999,13,8999.5,116993.5,3000.0,9000000.0,117000000.0
5,$10000 - ou+,10,10999.5,109995.0,5000.0,25000000.0,250000000.0

Media amostral: 5841.6 renda familiar
Desvio padrao amostral: 3224.9 renda familiar

In [20]:
'''
EXERCÍCIO 06
'''

# Notas no SAT

notas_sat = pd.DataFrame({'Notas_homens': [1520, 1750, 2120, 1380,
                                           1980, 1650, 1030, 1710],
                         'Notas_mulheres': [1790, 1510, 1500, 1950,
                                            2210, 1870, 1260, 1590]})
display(notas_sat)

# Cálculo das médias, desvios padrão e coeficiente de variação
est_notas = pd.DataFrame(notas_sat.mean(axis=0, numeric_only=True), columns=['Média'])
est_notas['DesvPad'] = notas_sat.std(axis=0, ddof=0, numeric_only=True)
est_notas['CV'] = est_notas['DesvPad']/est_notas['Média']*100
display(est_notas)

   Notas_homens  Notas_mulheres
0          1520            1790
1          1750            1510
2          2120            1500
3          1380            1950
4          1980            2210
5          1650            1870
6          1030            1260
7          1710            1590

                 Média     DesvPad         CV
Notas_homens    1642.5  319.599359  19.458104
Notas_mulheres  1710.0  282.975264  16.548261

In [21]:
# Média de rebatidas

rebatidas = pd.DataFrame({'Time A': [0.295, 0.310, 0.325, 0.272, 0.256,
                                     0.297, 0.320, 0.384, 0.235, 0.297],
                         'Time B': [0.223, 0.312, 0.256, 0.300, 0.238,
                                    0.299, 0.204, 0.226, 0.292, 0.260]})
display(rebatidas)

# Cálculo das médias, desvios padrão e coeficiente de variação
est_rebatidas = pd.DataFrame(rebatidas.mean(axis=0, numeric_only=True), columns=['Média'])
est_rebatidas['DesvPad'] = rebatidas.std(axis=0, ddof=0, numeric_only=True)
est_rebatidas['CV'] = est_rebatidas['DesvPad']/est_rebatidas['Média']*100
display(est_rebatidas)

   Time A  Time B
0   0.295   0.223
1   0.310   0.312
2   0.325   0.256
3   0.272   0.300
4   0.256   0.238
5   0.297   0.299
6   0.320   0.204
7   0.384   0.226
8   0.235   0.292
9   0.297   0.260

         Média   DesvPad         CV
Time A  0.2991  0.038937  13.018054
Time B  0.2610  0.036056  13.814373